import spacy
from spacy import displacy

nlp = spacy.load('en_core_web_sm')
doc = nlp('In 2011, Google launched Google +, its fourth foray into social networking.')

doc.user_data['title'] = 'An example of an entity visualization'

#instruct displacy to render the markup wrapped as a full HTML page
html = displacy.render(doc, style='ent', page=True)

# save the HTML file generated by displacy.render() to disk on your machine
from pathlib import Path

output_path = Path("visualizations/ent_visual.html") # must create visualizations folder first
# open the file we created and write the HTML into it (similar to fopen() and fwrite() in C)
output_path.open("w", encoding="utf-8").write(html)

# you can now go the visualizations folder and click on the file to view it in your broswer without
# having to boot up a server to see it
